### ISSUE TITLE
datatset

### ISSUE THREAD

**Issue by 0xArkin** [moonfire-ventures/tokenomics#9]
the project is very interesting! 
I have a question around the data, is it added manually or do you have an automation tool?

I'm looking to automate the analysis of tokenomics of hundreds of tokens (I'd like to avoid as much as possible to add the data manually)

**Comment by jonvet** [comment]
Hi and thanks for your feedback. It's currently a mainly manual task, but we're exploring ways to automate it. It's a tricky task because this data can come in many different formats as you probably know.
